[package]
name = "aoc_2021"
version = "0.1.0"
authors = ["Benjamin Jones <benjaminfjones@gmail.com>"]
edition = "2021"

[dependencies]
regex = "1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "d7"
harness = false
